name: Lint helm charts manifests
on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup helm
      uses: azure/setup-helm@v3
      with: { version: v3.11.1 }
    - name: Lint
      run: helm lint charts/*
